import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { OrganizationProvider } from "@/context/OrganizationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const staleChunkRecoveryScript = String.raw`
(function () {
  var storageKey = "arenzyra:stale-next-chunk-reload-at";
  var cooldownMs = 30000;
  var errorPattern = /ChunkLoadError|Loading chunk|Failed to fetch dynamically imported module|\/_next\/static\//i;

  function isNextStaticUrl(value) {
    return typeof value === "string" && value.indexOf("/_next/static/") !== -1;
  }

  function describe(value) {
    if (!value) {
      return "";
    }

    if (typeof value === "string") {
      return value;
    }

    if (typeof value.message === "string" && value.message) {
      return value.message;
    }

    if (typeof value.reason === "string" && value.reason) {
      return value.reason;
    }

    if (typeof value.stack === "string" && value.stack) {
      return value.stack;
    }

    try {
      return String(value);
    } catch {
      return "";
    }
  }

  function canReload() {
    try {
      var lastAttempt = Number(window.sessionStorage.getItem(storageKey) || "0");
      return !lastAttempt || Date.now() - lastAttempt > cooldownMs;
    } catch {
      return true;
    }
  }

  function markReload() {
    try {
      window.sessionStorage.setItem(storageKey, String(Date.now()));
    } catch {}
  }

  function reloadForAssetFailure(reason, url) {
    if (!canReload()) {
      return;
    }

    console.warn("[arenzyra-web] Reloading after stale Next asset failure.", {
      reason: reason,
      url: url,
    });
    markReload();
    window.location.reload();
  }

  window.addEventListener(
    "error",
    function (event) {
      var target = event.target;
      var scriptUrl =
        target && target.tagName === "SCRIPT" && typeof target.src === "string" ? target.src : "";
      var reason = describe(event.error) || describe(event.message);

      if (isNextStaticUrl(scriptUrl)) {
        reloadForAssetFailure(reason || "script-load-error", scriptUrl);
        return;
      }

      if (errorPattern.test(reason)) {
        reloadForAssetFailure(reason, scriptUrl);
      }
    },
    true
  );

  window.addEventListener("unhandledrejection", function (event) {
    var reason = describe(event.reason);
    if (errorPattern.test(reason)) {
      reloadForAssetFailure(reason, "");
    }
  });
})();
`;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="stale-chunk-recovery" strategy="beforeInteractive">
          {staleChunkRecoveryScript}
        </Script>
        <OrganizationProvider>
          <AuthProvider>{children}</AuthProvider>
        </OrganizationProvider>
      </body>
    </html>
  );
}
