// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/**
 * Prisma config in CommonJS-friendly syntax so the CLI can parse it without
 * TS/ESM loaders. Adjust here if you move the schema or migrations.
 */
import { config } from "dotenv";
import path from "node:path";
import { defineConfig } from "prisma/config";

// Load .env relative to project root
config({ path: path.join(__dirname, ".env") });

const databaseUrl = process.env.DATABASE_URL;
const shadowUrl = process.env.SHADOW_DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
    shadowDatabaseUrl: shadowUrl,
  },
});
